import type {
  AirClass,
  Assignment,
  ChapterNode,
  ChapterSyncLink,
  KnowledgePoint,
  Microlesson,
  Premium,
  Question,
  Textbook,
} from "./types"

export const SUBJECTS = ["数学", "语文", "英语", "物理", "化学", "生物"]
export const VERSIONS = ["人教版", "北师大版", "苏教版", "华师大版", "外研版"]
export const GRADES = ["一年级", "二年级", "三年级", "四年级", "五年级", "六年级", "七年级", "八年级", "九年级"]

export const textbooks: Textbook[] = [
  {
    id: "tb-1",
    name: "义务教育教科书·数学（七年级上册）",
    subject: "数学",
    stage: "junior",
    grade: "七年级",
    volume: "upper",
    version: "人教版",
    year: 2024,
    status: "published",
    cover: "/covers/math.png",
    updatedAt: "2026-05-12",
  },
  {
    id: "tb-2",
    name: "义务教育教科书·数学（七年级上册）",
    subject: "数学",
    stage: "junior",
    grade: "七年级",
    volume: "upper",
    version: "北师大版",
    year: 2024,
    status: "published",
    cover: "/covers/math.png",
    updatedAt: "2026-04-28",
  },
  {
    id: "tb-3",
    name: "义务教育教科书·数学（七年级上册）",
    subject: "数学",
    stage: "junior",
    grade: "七年级",
    volume: "upper",
    version: "人教版",
    year: 2019,
    status: "archived",
    cover: "/covers/math.png",
    updatedAt: "2025-09-01",
  },
  {
    id: "tb-4",
    name: "义务教育教科书·语文（八年级下册）",
    subject: "语文",
    stage: "junior",
    grade: "八年级",
    volume: "lower",
    version: "人教版",
    year: 2024,
    status: "published",
    cover: "/covers/chinese.png",
    updatedAt: "2026-03-15",
  },
  {
    id: "tb-5",
    name: "普通高中教科书·物理（必修第一册）",
    subject: "物理",
    stage: "senior",
    grade: "高一",
    volume: "full",
    version: "人教版",
    year: 2025,
    status: "draft",
    cover: "/covers/physics.png",
    updatedAt: "2026-06-10",
  },
]

// 知识点：数学七上的稳定考点，跨版本通用
export const knowledgePoints: KnowledgePoint[] = [
  { id: "kp-1", subject: "数学", group: "有理数", name: "正数与负数的概念" },
  { id: "kp-2", subject: "数学", group: "有理数", name: "数轴与相反数" },
  { id: "kp-3", subject: "数学", group: "有理数", name: "有理数的加减运算" },
  { id: "kp-4", subject: "数学", group: "有理数", name: "有理数的乘除运算" },
  { id: "kp-5", subject: "数学", group: "整式", name: "单项式与多项式" },
  { id: "kp-6", subject: "数学", group: "整式", name: "整式的加减" },
  { id: "kp-7", subject: "数学", group: "一元一次方程", name: "方程的概念" },
  { id: "kp-8", subject: "数学", group: "一元一次方程", name: "解一元一次方程" },
]

// 章节目录：每个节点声明它覆盖的知识点
export const chapters: ChapterNode[] = [
  // 人教版数学七上（tb-1）
  { id: "ch-1", textbookId: "tb-1", parentId: null, title: "第一章 有理数", order: 1, knowledgePointIds: [] },
  { id: "ch-1-1", textbookId: "tb-1", parentId: "ch-1", title: "1.1 正数和负数", order: 1, knowledgePointIds: ["kp-1"] },
  { id: "ch-1-2", textbookId: "tb-1", parentId: "ch-1", title: "1.2 有理数", order: 2, knowledgePointIds: ["kp-2"] },
  { id: "ch-1-3", textbookId: "tb-1", parentId: "ch-1", title: "1.3 有理数的加减法", order: 3, knowledgePointIds: ["kp-3"] },
  { id: "ch-1-4", textbookId: "tb-1", parentId: "ch-1", title: "1.4 有理数的乘除法", order: 4, knowledgePointIds: ["kp-4"] },
  { id: "ch-2", textbookId: "tb-1", parentId: null, title: "第二章 整式的加减", order: 2, knowledgePointIds: [] },
  { id: "ch-2-1", textbookId: "tb-1", parentId: "ch-2", title: "2.1 整式", order: 1, knowledgePointIds: ["kp-5"] },
  { id: "ch-2-2", textbookId: "tb-1", parentId: "ch-2", title: "2.2 整式的加减", order: 2, knowledgePointIds: ["kp-6"] },
  { id: "ch-3", textbookId: "tb-1", parentId: null, title: "第三章 一元一次方程", order: 3, knowledgePointIds: [] },
  { id: "ch-3-1", textbookId: "tb-1", parentId: "ch-3", title: "3.1 从算式到方程", order: 1, knowledgePointIds: ["kp-7"] },
  { id: "ch-3-2", textbookId: "tb-1", parentId: "ch-3", title: "3.2 解一元一次方程", order: 2, knowledgePointIds: ["kp-8"] },
  // 北师大版数学七上（tb-2，结构不同，知识点对应一致）
  { id: "bs-1", textbookId: "tb-2", parentId: null, title: "第一章 丰富的图形世界", order: 1, knowledgePointIds: [] },
  { id: "bs-2", textbookId: "tb-2", parentId: null, title: "第二章 有理数及其运算", order: 2, knowledgePointIds: [] },
  { id: "bs-2-1", textbookId: "tb-2", parentId: "bs-2", title: "2.1 有理数", order: 1, knowledgePointIds: ["kp-1"] },
  { id: "bs-2-2", textbookId: "tb-2", parentId: "bs-2", title: "2.2 数轴", order: 2, knowledgePointIds: ["kp-2"] },
  { id: "bs-2-3", textbookId: "tb-2", parentId: "bs-2", title: "2.3 有理数的加减法", order: 3, knowledgePointIds: ["kp-3"] },
  { id: "bs-2-4", textbookId: "tb-2", parentId: "bs-2", title: "2.4 有理数的乘除法", order: 4, knowledgePointIds: ["kp-4"] },
  { id: "bs-3", textbookId: "tb-2", parentId: null, title: "第三章 整式及其加减", order: 3, knowledgePointIds: ["kp-5", "kp-6"] },
  // 2019 旧人教版数学七上（tb-3）
  { id: "old-1", textbookId: "tb-3", parentId: null, title: "第一章 有理数", order: 1, knowledgePointIds: [] },
  { id: "old-1-1", textbookId: "tb-3", parentId: "old-1", title: "1.1 正数和负数", order: 1, knowledgePointIds: ["kp-1"] },
  { id: "old-1-2", textbookId: "tb-3", parentId: "old-1", title: "1.2 有理数", order: 2, knowledgePointIds: ["kp-2"] },
  { id: "old-2", textbookId: "tb-3", parentId: null, title: "第二章 整式的加减", order: 2, knowledgePointIds: [] },
  { id: "old-2-1", textbookId: "tb-3", parentId: "old-2", title: "2.1 整式", order: 1, knowledgePointIds: ["kp-5"] },
]

// 题目：打知识点标签，章节锚点可由知识点自动归集；带级别/归属
export const questions: Question[] = [
  {
    id: "q-1",
    stem: "下列各数中，是负数的是（　）。",
    type: "single",
    subject: "数学",
    difficulty: 1,
    level: "city",
    ownerScope: "上海市",
    options: [
      { key: "A", content: "$-3$" },
      { key: "B", content: "$0$" },
      { key: "C", content: "$2.5$" },
      { key: "D", content: "$|-1|$" },
    ],
    answer: "A",
    analysis: "负数是小于 0 的数，$-3 < 0$，故选 A。",
    knowledgePointIds: ["kp-1"],
    literacy: ["数学运算"],
    cognitive: "理解",
    usage: ["基础巩固", "课堂讲解"],
    scene: "纯数学情景",
    videoTitle: "认识负数与相反数",
    videoDuration: "06:12",
    usedCount: 326,
    studentCount: 1280,
    chapterMounts: [
      { textbookId: "tb-1", chapterId: "ch-1-1" },
      { textbookId: "tb-2", chapterId: "bs-2-1" },
    ],
    updatedAt: "2026-05-20",
  },
  {
    id: "q-2",
    stem: "计算：$(-7) + (+3) - (-5) = $ ______。",
    type: "fill",
    subject: "数学",
    difficulty: 2,
    level: "city",
    ownerScope: "上海市",
    answer: "$1$",
    analysis: "原式 $= -7 + 3 + 5 = 1$。",
    knowledgePointIds: ["kp-3"],
    literacy: ["数学运算"],
    cognitive: "应用",
    usage: ["课后练习"],
    videoTitle: "有理数加减混合运算",
    videoDuration: "08:30",
    usedCount: 91,
    studentCount: 540,
    chapterMounts: [
      { textbookId: "tb-1", chapterId: "ch-1-3" },
      { textbookId: "tb-2", chapterId: "bs-2-3" },
    ],
    updatedAt: "2026-05-18",
  },
  {
    id: "q-3",
    stem: "判断：两个负数相乘，积一定为正数。（　）",
    type: "judge",
    subject: "数学",
    difficulty: 2,
    level: "city",
    ownerScope: "上海市",
    answer: "正确",
    knowledgePointIds: ["kp-4"],
    chapterMounts: [
      { textbookId: "tb-1", chapterId: "ch-1-4" },
      { textbookId: "tb-2", chapterId: "bs-2-4" },
    ],
    updatedAt: "2026-05-15",
  },
  {
    id: "q-4",
    stem: "解方程：3x − 5 = 2x + 7，并写出完整求解过程。",
    type: "subjective",
    subject: "数学",
    difficulty: 3,
    level: "district",
    ownerScope: "徐汇区",
    answer: "x = 12",
    knowledgePointIds: ["kp-8"],
    chapterMounts: [{ textbookId: "tb-1", chapterId: "ch-3-2" }],
    updatedAt: "2026-06-01",
  },
  {
    id: "q-5",
    stem: "下列式子中，属于单项式的有（　）。",
    type: "multiple",
    subject: "数学",
    difficulty: 3,
    level: "city",
    ownerScope: "上海市",
    knowledgePointIds: ["kp-5"],
    chapterMounts: [
      { textbookId: "tb-1", chapterId: "ch-2-1" },
      { textbookId: "tb-2", chapterId: "bs-3" },
    ],
    updatedAt: "2026-06-08",
  },
  {
    id: "q-6",
    stem: "在数轴上，表示 −2 的点到原点的距离是 ______。",
    type: "fill",
    subject: "数学",
    difficulty: 1,
    level: "school",
    ownerScope: "上海市实验中学",
    answer: "2",
    knowledgePointIds: ["kp-2"],
    chapterMounts: [
      { textbookId: "tb-1", chapterId: "ch-1-2" },
      { textbookId: "tb-2", chapterId: "bs-2-2" },
    ],
    updatedAt: "2026-06-09",
  },
  {
    id: "q-7",
    stem: "计算：(−12) ÷ (−4) × 3 = ______。",
    type: "fill",
    subject: "数学",
    difficulty: 2,
    level: "district",
    ownerScope: "浦东新区",
    answer: "9",
    knowledgePointIds: ["kp-4"],
    chapterMounts: [{ textbookId: "tb-1", chapterId: "ch-1-4" }],
    updatedAt: "2026-06-09",
  },
  {
    id: "q-8",
    stem: "合并同类项：3a + 5a − 2a = ______。",
    type: "fill",
    subject: "数学",
    difficulty: 2,
    level: "school",
    ownerScope: "上海市实验中学",
    answer: "6a",
    knowledgePointIds: ["kp-6"],
    chapterMounts: [],
    updatedAt: "2026-06-11",
  },
  {
    id: "q-9",
    stem: "下列各式是方程的是（　）。A. 3+2  B. x−1=0  C. a>b  D. 2x",
    type: "single",
    subject: "数学",
    difficulty: 1,
    level: "city",
    ownerScope: "上海市",
    answer: "B",
    knowledgePointIds: ["kp-7"],
    chapterMounts: [],
    updatedAt: "2026-06-11",
  },
  {
    id: "q-10",
    stem: "若 |x| = 5，则 x = ______。",
    type: "fill",
    subject: "数学",
    difficulty: 2,
    level: "city",
    ownerScope: "上海市",
    answer: "±5",
    knowledgePointIds: ["kp-1", "kp-2"],
    chapterMounts: [],
    updatedAt: "2026-06-12",
  },
]

// 教材同步关系：人教版（tb-1） ⇄ 北师大版（tb-2），逐目录手工对应
export const syncLinks: ChapterSyncLink[] = [
  {
    id: "sl-1",
    fromTextbookId: "tb-1",
    fromChapterId: "ch-1-1",
    toTextbookId: "tb-2",
    toChapterId: "bs-2-1",
    syncTypes: ["question", "assignment"],
  },
  {
    id: "sl-2",
    fromTextbookId: "tb-1",
    fromChapterId: "ch-1-3",
    toTextbookId: "tb-2",
    toChapterId: "bs-2-3",
    syncTypes: ["question", "assignment", "microlesson"],
  },
  {
  id: "sl-3",
  fromTextbookId: "tb-1",
  fromChapterId: "ch-2-1",
  toTextbookId: "tb-2",
  toChapterId: "bs-3",
  syncTypes: ["question", "microlesson", "airclass"],
  },
  // tb-1 同时同步到 tb-3（一对多：同一主教材 → 多套目标教材）
  {
  id: "sl-4",
  fromTextbookId: "tb-1",
  fromChapterId: "ch-1-1",
  toTextbookId: "tb-3",
  toChapterId: "old-1-1",
  syncTypes: ["question", "assignment"],
  },
  {
  id: "sl-5",
  fromTextbookId: "tb-1",
  fromChapterId: "ch-2-1",
  toTextbookId: "tb-3",
  toChapterId: "old-2-1",
  syncTypes: ["question"],
  },
  ]

export const assignments: Assignment[] = [
  {
    id: "as-1",
    title: "第一章 有理数 · 课后基础练",
    subject: "数学",
    level: "city",
    ownerScope: "上海市",
    questionIds: ["q-1", "q-2", "q-3"],
    textbookIds: ["tb-1", "tb-2"],
    knowledgePointIds: ["kp-1", "kp-2"],
    chapterMounts: [{ textbookId: "tb-1", chapterId: "ch-1-1" }],
    status: "published",
    assignedClasses: 6,
    usedCount: 142,
    updatedAt: "2026-05-22",
  },
  {
    id: "as-2",
    title: "一元一次方程 · 专项提升",
    subject: "数学",
    level: "district",
    ownerScope: "徐汇区",
    questionIds: ["q-4"],
    textbookIds: ["tb-1"],
    knowledgePointIds: ["kp-7", "kp-8"],
    chapterMounts: [{ textbookId: "tb-1", chapterId: "ch-3-1" }],
    status: "draft",
    updatedAt: "2026-06-02",
  },
  {
    id: "as-3",
    title: "整式的加减 · 随堂练习",
    subject: "数学",
    level: "school",
    ownerScope: "上海市实验中学",
    questionIds: ["q-5", "q-8"],
    textbookIds: ["tb-1"],
    knowledgePointIds: ["kp-5", "kp-6"],
    chapterMounts: [],
    status: "draft",
    updatedAt: "2026-06-10",
  },
]

// 微课
export const microlessons: Microlesson[] = [
  {
    id: "ml-1",
    title: "认识负数与数轴",
    subject: "数学",
    duration: "06:42",
    level: "city",
    ownerScope: "上海市",
    viewCount: 2310,
    knowledgePointIds: ["kp-1", "kp-2"],
    chapterMounts: [{ textbookId: "tb-1", chapterId: "ch-1-1" }],
    updatedAt: "2026-05-18",
  },
  {
    id: "ml-2",
    title: "有理数的乘除法则精讲",
    subject: "数学",
    duration: "09:15",
    level: "city",
    ownerScope: "上海市",
    knowledgePointIds: ["kp-4"],
    chapterMounts: [{ textbookId: "tb-1", chapterId: "ch-1-4" }],
    updatedAt: "2026-05-25",
  },
  {
    id: "ml-3",
    title: "合并同类项技巧",
    subject: "数学",
    duration: "07:08",
    level: "school",
    ownerScope: "徐汇区第一中心小学",
    knowledgePointIds: ["kp-6"],
    chapterMounts: [],
    updatedAt: "2026-06-05",
  },
]

// 空中课堂
export const airClasses: AirClass[] = [
  {
    id: "ac-1",
    title: "有理数运算综合复习课",
    subject: "数学",
    teacher: "王明老师",
    level: "city",
    ownerScope: "上海市",
    scheduledAt: "2026-06-25 19:00",
    knowledgePointIds: ["kp-3", "kp-4"],
    chapterMounts: [{ textbookId: "tb-1", chapterId: "ch-1-3" }],
    updatedAt: "2026-05-20",
  },
  {
    id: "ac-2",
    title: "整式概念与化简专题",
    subject: "数学",
    teacher: "李芳老师",
    level: "city",
    ownerScope: "上海市",
    scheduledAt: "2026-06-28 19:00",
    knowledgePointIds: ["kp-5", "kp-6"],
    chapterMounts: [],
    updatedAt: "2026-06-07",
  },
]

// 精品资源（独立类型）：平台/区域精选优质资源包
export const premiums: Premium[] = [
  {
    id: "pm-1",
    title: "七年级（上）有理数单元精品卷",
    subject: "数学",
    category: "paper",
    description: "覆盖有理数全部核心考点的精选试卷，含分层难度与详解。",
    questionIds: ["q-1", "q-2", "q-3"],
    knowledgePointIds: ["kp-1", "kp-2", "kp-3"],
    level: "city",
    ownerScope: "上海市",
    chapterMounts: [{ textbookId: "tb-1", chapterId: "ch-1-1" }],
    usedCount: 218,
    updatedAt: "2026-05-28",
  },
  {
    id: "pm-2",
    title: "一元一次方程易错题专题",
    subject: "数学",
    category: "special",
    description: "汇集典型易错题与变式训练，配套讲解视频。",
    questionIds: ["q-9", "q-10"],
    knowledgePointIds: ["kp-7"],
    level: "district",
    ownerScope: "徐汇区",
    chapterMounts: [],
    usedCount: 96,
    updatedAt: "2026-06-05",
  },
  {
    id: "pm-3",
    title: "整式运算精品课件",
    subject: "数学",
    category: "courseware",
    description: "可直接用于课堂讲授的整式运算精品课件。",
    questionIds: [],
    knowledgePointIds: ["kp-5", "kp-6"],
    level: "school",
    ownerScope: "位育中学",
    chapterMounts: [],
    usedCount: 34,
    updatedAt: "2026-06-09",
  },
]
