import type {
  AirClass,
  Assignment,
  ChapterNode,
  ChapterSyncLink,
  KnowledgePoint,
  Microlesson,
  Premium,
  Question,
  QuestionVersion,
  TagDisable,
  TagItem,
  Textbook,
} from "./types"
import { BASE_SCOPE } from "./types"

export const SUBJECTS = ["数学", "语文", "英语", "物理", "化学", "生物"]
export const VERSIONS = ["人教版", "北师大版", "苏教版", "华师大版", "外研版"]
export const GRADES = ["一年级", "二年级", "三年级", "四年级", "五年级", "六年级", "七年级", "八年级", "九年级"]

export const textbooks: Textbook[] = [
  {
    id: "tb-1",
    name: "义务教育教科书·数学（七年级上册）",
    subject: "数学",
    stage: "junior",
    grade: "七年级",
    volume: "upper",
    version: "人教版",
    year: 2024,
    status: "published",
    cover: "/covers/math.png",
    updatedAt: "2026-05-12",
  },
  {
    id: "tb-2",
    name: "义务教育教科书·数学（七年级上册）",
    subject: "数学",
    stage: "junior",
    grade: "七年级",
    volume: "upper",
    version: "北师大版",
    year: 2024,
    status: "published",
    cover: "/covers/math.png",
    updatedAt: "2026-04-28",
  },
  {
    id: "tb-3",
    name: "义务教育教科书·数学（七年级上册）",
    subject: "数学",
    stage: "junior",
    grade: "七年级",
    volume: "upper",
    version: "人教版",
    year: 2019,
    status: "archived",
    cover: "/covers/math.png",
    updatedAt: "2025-09-01",
  },
  {
    id: "tb-4",
    name: "义务教育教科书·语文（八年级下册）",
    subject: "语文",
    stage: "junior",
    grade: "八年级",
    volume: "lower",
    version: "人教版",
    year: 2024,
    status: "published",
    cover: "/covers/chinese.png",
    updatedAt: "2026-03-15",
  },
  {
    id: "tb-5",
    name: "普通高中教科书·物理（必修第一册）",
    subject: "物理",
    stage: "senior",
    grade: "高一",
    volume: "full",
    version: "人教版",
    year: 2025,
    status: "draft",
    cover: "/covers/physics.png",
    updatedAt: "2026-06-10",
  },
]

// 知识点：数学七上的稳定考点，跨版本通用
export const knowledgePoints: KnowledgePoint[] = [
  { id: "kp-1", subject: "数学", group: "有理数", name: "正数与负数的概念" },
  { id: "kp-2", subject: "数学", group: "有理数", name: "数轴与相反数" },
  { id: "kp-3", subject: "数学", group: "有理数", name: "有理数的加减运算" },
  { id: "kp-4", subject: "数学", group: "有理数", name: "有理数的乘除运算" },
  { id: "kp-5", subject: "数学", group: "整式", name: "单项式与多项式" },
  { id: "kp-6", subject: "数学", group: "整式", name: "整式的加减" },
  { id: "kp-7", subject: "数学", group: "一元一次方程", name: "方程的概念" },
  { id: "kp-8", subject: "数学", group: "一元一次方程", name: "解一元一次方程" },
]

// ===================== 标签字典种子 =====================
// 平台基准（BASE_SCOPE）：所有区域共享；区域可新增专属或停用基准项。
let _tagSeq = 0
const _t = (
  dimensionKey: TagItem["dimensionKey"],
  subject: string,
  name: string,
  order: number,
  scope: string,
  tier?: number,
): TagItem => ({ id: `tag-${++_tagSeq}`, dimensionKey, subject, name, order, scope, tier })

export const tagItems: TagItem[] = [
  // 难度（通用标准，可自定义档位）
  _t("difficulty", "通用", "1星·入门", 1, BASE_SCOPE, 1),
  _t("difficulty", "通用", "2星·基础", 2, BASE_SCOPE, 2),
  _t("difficulty", "通用", "3星·中等", 3, BASE_SCOPE, 3),
  _t("difficulty", "通用", "4星·较难", 4, BASE_SCOPE, 4),
  _t("difficulty", "通用", "5星·挑战", 5, BASE_SCOPE, 5),
  // 学习水平（通用标准，单选）
  _t("learningLevel", "通用", "记忆", 1, BASE_SCOPE),
  _t("learningLevel", "通用", "理解", 2, BASE_SCOPE),
  _t("learningLevel", "通用", "应用", 3, BASE_SCOPE),
  _t("learningLevel", "通用", "分析综合", 4, BASE_SCOPE),
  // 内容领域（数学，多选）
  _t("contentDomain", "数学", "数与代数", 1, BASE_SCOPE),
  _t("contentDomain", "数学", "图形与几何", 2, BASE_SCOPE),
  _t("contentDomain", "数学", "统计与概率", 3, BASE_SCOPE),
  _t("contentDomain", "数学", "综合与实践", 4, BASE_SCOPE),
  // 核心素养（数学，多选）
  _t("literacy", "数学", "数学运算", 1, BASE_SCOPE),
  _t("literacy", "数学", "逻辑推理", 2, BASE_SCOPE),
  _t("literacy", "数学", "数学建模", 3, BASE_SCOPE),
  _t("literacy", "数学", "直观想象", 4, BASE_SCOPE),
  _t("literacy", "数学", "数据分析", 5, BASE_SCOPE),
  // 情境属性（数学，单选）
  _t("scene", "数学", "纯数学情境", 1, BASE_SCOPE),
  _t("scene", "数学", "生活情境", 2, BASE_SCOPE),
  _t("scene", "数学", "跨学科情境", 3, BASE_SCOPE),
  // 教学用途（数学，多选）
  _t("usage", "数学", "基础巩固", 1, BASE_SCOPE),
  _t("usage", "数学", "易错训练", 2, BASE_SCOPE),
  _t("usage", "数学", "课堂讲解", 3, BASE_SCOPE),
  _t("usage", "数学", "单元复习", 4, BASE_SCOPE),
  _t("usage", "数学", "拓展提升", 5, BASE_SCOPE),
  // —— 区域专属示例：徐汇区为数学“核心素养”新增本区标签 ——
  _t("literacy", "数学", "区域特色·实验探究", 6, "徐汇区"),
  // —— 区域专属示例：上海市为数学“情境属性”新增 ——
  _t("scene", "数学", "海派文化情境", 4, "上海市"),
]

// 区域停用覆盖示例：徐汇区停用基准“跨学科情境”
export const tagDisables: TagDisable[] = [
  { tagId: tagItems.find((t) => t.scope === BASE_SCOPE && t.name === "跨学科情境")!.id, scope: "徐汇区" },
]

// 章节目录：每个节点声明它覆盖的知识点
export const chapters: ChapterNode[] = [
  // 人教版数学七上（tb-1）
  { id: "ch-1", textbookId: "tb-1", parentId: null, title: "第一章 有理数", order: 1, knowledgePointIds: [] },
  { id: "ch-1-1", textbookId: "tb-1", parentId: "ch-1", title: "1.1 正数和负数", order: 1, knowledgePointIds: ["kp-1"] },
  { id: "ch-1-2", textbookId: "tb-1", parentId: "ch-1", title: "1.2 有理数", order: 2, knowledgePointIds: ["kp-2"] },
  { id: "ch-1-3", textbookId: "tb-1", parentId: "ch-1", title: "1.3 有理数的加减法", order: 3, knowledgePointIds: ["kp-3"] },
  { id: "ch-1-4", textbookId: "tb-1", parentId: "ch-1", title: "1.4 有理数的乘除法", order: 4, knowledgePointIds: ["kp-4"] },
  { id: "ch-2", textbookId: "tb-1", parentId: null, title: "第二章 整式的加减", order: 2, knowledgePointIds: [] },
  { id: "ch-2-1", textbookId: "tb-1", parentId: "ch-2", title: "2.1 整式", order: 1, knowledgePointIds: ["kp-5"] },
  { id: "ch-2-2", textbookId: "tb-1", parentId: "ch-2", title: "2.2 整式的加减", order: 2, knowledgePointIds: ["kp-6"] },
  { id: "ch-3", textbookId: "tb-1", parentId: null, title: "第三章 一元一次方程", order: 3, knowledgePointIds: [] },
  { id: "ch-3-1", textbookId: "tb-1", parentId: "ch-3", title: "3.1 从算式到方程", order: 1, knowledgePointIds: ["kp-7"] },
  { id: "ch-3-2", textbookId: "tb-1", parentId: "ch-3", title: "3.2 解一元一次方程", order: 2, knowledgePointIds: ["kp-8"] },
  // 北师大版数学七上（tb-2，结构不同，知识点对应一致）
  { id: "bs-1", textbookId: "tb-2", parentId: null, title: "第一章 丰富的图形世界", order: 1, knowledgePointIds: [] },
  { id: "bs-2", textbookId: "tb-2", parentId: null, title: "第二章 有理数及其运算", order: 2, knowledgePointIds: [] },
  { id: "bs-2-1", textbookId: "tb-2", parentId: "bs-2", title: "2.1 有理数", order: 1, knowledgePointIds: ["kp-1"] },
  { id: "bs-2-2", textbookId: "tb-2", parentId: "bs-2", title: "2.2 数轴", order: 2, knowledgePointIds: ["kp-2"] },
  { id: "bs-2-3", textbookId: "tb-2", parentId: "bs-2", title: "2.3 有理数的加减法", order: 3, knowledgePointIds: ["kp-3"] },
  { id: "bs-2-4", textbookId: "tb-2", parentId: "bs-2", title: "2.4 有理数的乘除法", order: 4, knowledgePointIds: ["kp-4"] },
  { id: "bs-3", textbookId: "tb-2", parentId: null, title: "第三章 整式及其加减", order: 3, knowledgePointIds: ["kp-5", "kp-6"] },
  // 2019 旧人教版数学七上（tb-3）
  { id: "old-1", textbookId: "tb-3", parentId: null, title: "第一章 有理数", order: 1, knowledgePointIds: [] },
  { id: "old-1-1", textbookId: "tb-3", parentId: "old-1", title: "1.1 正数和负数", order: 1, knowledgePointIds: ["kp-1"] },
  { id: "old-1-2", textbookId: "tb-3", parentId: "old-1", title: "1.2 有理数", order: 2, knowledgePointIds: ["kp-2"] },
  { id: "old-2", textbookId: "tb-3", parentId: null, title: "第二章 整式的加减", order: 2, knowledgePointIds: [] },
  { id: "old-2-1", textbookId: "tb-3", parentId: "old-2", title: "2.1 整式", order: 1, knowledgePointIds: ["kp-5"] },
]

// 题目：打知识点标签，章节锚点可由知识点自动归集；带级别/归属
// rawQuestions 不含版本结构，下方 normalizeQuestion 会自动补 v1（含历史演示版本）
const rawQuestions: Omit<Question, "version" | "versions">[] = [
  {
    id: "q-1",
    stem: "下列各数中，是负数的是（　）。",
    type: "single",
    subject: "数学",
    difficulty: 1,
    level: "city",
    ownerScope: "上海市",
    options: [
      { key: "A", content: "$-3$" },
      { key: "B", content: "$0$" },
      { key: "C", content: "$2.5$" },
      { key: "D", content: "$|-1|$" },
    ],
    answer: "A",
    analysis: "负数是小于 0 的数，$-3 < 0$，故选 A。",
    knowledgePointIds: ["kp-1"],
    literacy: ["数学运算"],
    cognitive: "理解",
    usage: ["基础巩固", "课堂讲解"],
    scene: "纯数学情景",
    videoTitle: "认识负数与相反数",
    videoDuration: "06:12",
    usedCount: 326,
    studentCount: 1280,
    chapterMounts: [
      { textbookId: "tb-1", chapterId: "ch-1-1" },
      { textbookId: "tb-2", chapterId: "bs-2-1" },
    ],
    updatedAt: "2026-05-20",
  },
  {
    id: "q-2",
    stem: "计算：$(-7) + (+3) - (-5) = $ ______。",
    type: "fill",
    subject: "数学",
    difficulty: 2,
    level: "city",
    ownerScope: "上海市",
    answer: "$1$",
    analysis: "原式 $= -7 + 3 + 5 = 1$。",
    knowledgePointIds: ["kp-3"],
    literacy: ["数学运算"],
    cognitive: "应用",
    usage: ["课后练习"],
    videoTitle: "有理数加减混合运算",
    videoDuration: "08:30",
    usedCount: 91,
    studentCount: 540,
    chapterMounts: [
      { textbookId: "tb-1", chapterId: "ch-1-3" },
      { textbookId: "tb-2", chapterId: "bs-2-3" },
    ],
    updatedAt: "2026-05-18",
  },
  {
    id: "q-3",
    stem: "判断：两个负数相乘，积一定为正数。（　）",
    type: "judge",
    subject: "数学",
    difficulty: 2,
    level: "city",
    ownerScope: "上海市",
    answer: "正确",
    knowledgePointIds: ["kp-4"],
    chapterMounts: [
      { textbookId: "tb-1", chapterId: "ch-1-4" },
      { textbookId: "tb-2", chapterId: "bs-2-4" },
    ],
    updatedAt: "2026-05-15",
  },
  {
    id: "q-4",
    stem: "解方程：3x − 5 = 2x + 7，并写出完整求解过程。",
    type: "subjective",
    subject: "数学",
    difficulty: 3,
    level: "district",
    ownerScope: "徐汇区",
    answer: "x = 12",
    knowledgePointIds: ["kp-8"],
    chapterMounts: [{ textbookId: "tb-1", chapterId: "ch-3-2" }],
    updatedAt: "2026-06-01",
  },
  {
    id: "q-5",
    stem: "下列式子中，属于单项式的有（　）。",
    type: "multiple",
    subject: "数学",
    difficulty: 3,
    level: "city",
    ownerScope: "上海市",
    knowledgePointIds: ["kp-5"],
    chapterMounts: [
      { textbookId: "tb-1", chapterId: "ch-2-1" },
      { textbookId: "tb-2", chapterId: "bs-3" },
    ],
    updatedAt: "2026-06-08",
  },
  {
    id: "q-6",
    stem: "在数轴上，表示 −2 的点到原点的距离是 ______。",
    type: "fill",
    subject: "数学",
    difficulty: 1,
    level: "school",
    ownerScope: "上海市实验中学",
    answer: "2",
    knowledgePointIds: ["kp-2"],
    chapterMounts: [
      { textbookId: "tb-1", chapterId: "ch-1-2" },
      { textbookId: "tb-2", chapterId: "bs-2-2" },
    ],
    updatedAt: "2026-06-09",
  },
  {
    id: "q-7",
    stem: "计算：(−12) ÷ (−4) × 3 = ______。",
    type: "fill",
    subject: "数学",
    difficulty: 2,
    level: "district",
    ownerScope: "浦东新区",
    answer: "9",
    knowledgePointIds: ["kp-4"],
    chapterMounts: [{ textbookId: "tb-1", chapterId: "ch-1-4" }],
    updatedAt: "2026-06-09",
  },
  {
    id: "q-8",
    stem: "合并同类项：3a + 5a − 2a = ______。",
    type: "fill",
    subject: "数学",
    difficulty: 2,
    level: "school",
    ownerScope: "上海市实验中学",
    answer: "6a",
    knowledgePointIds: ["kp-6"],
    chapterMounts: [],
    updatedAt: "2026-06-11",
  },
  {
    id: "q-9",
    stem: "下列各式是方程的是（　）。A. 3+2  B. x−1=0  C. a>b  D. 2x",
    type: "single",
    subject: "数学",
    difficulty: 1,
    level: "city",
    ownerScope: "上海市",
    answer: "B",
    knowledgePointIds: ["kp-7"],
    chapterMounts: [],
    updatedAt: "2026-06-11",
  },
  {
    id: "q-10",
    stem: "若 |x| = 5，则 x = ______。",
    type: "fill",
    subject: "数学",
    difficulty: 2,
    level: "city",
    ownerScope: "上海市",
    answer: "±5",
    knowledgePointIds: ["kp-1", "kp-2"],
    chapterMounts: [],
    updatedAt: "2026-06-12",
  },
]

// 为每道原始题目补一个 v1（镜像顶层内容与统计），使旧数据自然拥有版本结构
function normalizeQuestion(raw: Omit<Question, "version" | "versions">): Question {
  const v1: QuestionVersion = {
    version: 1,
    status: "published",
    stem: raw.stem,
    type: raw.type,
    options: raw.options,
    answer: raw.answer,
    analysis: raw.analysis,
    usedCount: raw.usedCount,
    studentCount: raw.studentCount,
    correctRate: undefined,
    changeNote: "初始版本",
    createdAt: raw.updatedAt,
  }
  return { ...raw, version: 1, versions: [v1] }
}

// 多版本演示：q-1 经历过一次修订（v1 表述不清 → v2 改好，正确率提升）
const MULTI_VERSION: Record<string, QuestionVersion[]> = {
  "q-1": [
    {
      version: 1,
      status: "archived",
      stem: "下列各数中，哪个是负数？",
      type: "single",
      options: [
        { key: "A", content: "$-3$" },
        { key: "B", content: "$0$" },
        { key: "C", content: "$2.5$" },
        { key: "D", content: "$|-1|$" },
      ],
      answer: "A",
      analysis: "负数是小于 0 的数。",
      usedCount: 120,
      studentCount: 460,
      correctRate: 63,
      changeNote: "初始版本",
      createdAt: "2026-03-10",
    },
    {
      version: 2,
      status: "published",
      stem: "下列各数中，是负数的是（　）。",
      type: "single",
      options: [
        { key: "A", content: "$-3$" },
        { key: "B", content: "$0$" },
        { key: "C", content: "$2.5$" },
        { key: "D", content: "$|-1|$" },
      ],
      answer: "A",
      analysis: "负数是小于 0 的数，$-3 < 0$，故选 A。",
      usedCount: 206,
      studentCount: 820,
      correctRate: 81,
      changeNote: "优化题干表述，明确选项作答方式，正确率由 63% 提升至 81%",
      createdAt: "2026-05-20",
    },
  ],
}

export const questions: Question[] = rawQuestions.map((raw) => {
  const multi = MULTI_VERSION[raw.id]
  if (!multi) return normalizeQuestion(raw)
  const current = multi[multi.length - 1]
  return {
    ...raw,
    // 顶层内容/统计镜像当前版本
    stem: current.stem,
    type: current.type,
    options: current.options,
    answer: current.answer,
    analysis: current.analysis,
    usedCount: current.usedCount,
    studentCount: current.studentCount,
    version: current.version,
    versions: multi,
  }
})

// 教材同步关系：人教版（tb-1） ⇄ 北师大版（tb-2），逐目录手工对应
export const syncLinks: ChapterSyncLink[] = [
  {
    id: "sl-1",
    fromTextbookId: "tb-1",
    fromChapterId: "ch-1-1",
    toTextbookId: "tb-2",
    toChapterId: "bs-2-1",
    syncTypes: ["question", "assignment"],
  },
  {
    id: "sl-2",
    fromTextbookId: "tb-1",
    fromChapterId: "ch-1-3",
    toTextbookId: "tb-2",
    toChapterId: "bs-2-3",
    syncTypes: ["question", "assignment", "microlesson"],
  },
  {
  id: "sl-3",
  fromTextbookId: "tb-1",
  fromChapterId: "ch-2-1",
  toTextbookId: "tb-2",
  toChapterId: "bs-3",
  syncTypes: ["question", "microlesson", "airclass"],
  },
  // tb-1 同时同步到 tb-3（一对多：同一主教材 → 多套目标教材）
  {
  id: "sl-4",
  fromTextbookId: "tb-1",
  fromChapterId: "ch-1-1",
  toTextbookId: "tb-3",
  toChapterId: "old-1-1",
  syncTypes: ["question", "assignment"],
  },
  {
  id: "sl-5",
  fromTextbookId: "tb-1",
  fromChapterId: "ch-2-1",
  toTextbookId: "tb-3",
  toChapterId: "old-2-1",
  syncTypes: ["question"],
  },
  ]

export const assignments: Assignment[] = [
  {
    id: "as-1",
    title: "第一章 有理数 · 课后基础练",
    subject: "数学",
    level: "city",
    ownerScope: "上海市",
    questionIds: ["q-1", "q-2", "q-3"],
    textbookIds: ["tb-1", "tb-2"],
    knowledgePointIds: ["kp-1", "kp-2"],
    chapterMounts: [{ textbookId: "tb-1", chapterId: "ch-1-1" }],
    status: "published",
    assignedClasses: 6,
    usedCount: 142,
    updatedAt: "2026-05-22",
  },
  {
    id: "as-2",
    title: "一元一次方程 · 专项提升",
    subject: "数学",
    level: "district",
    ownerScope: "徐汇区",
    questionIds: ["q-4"],
    textbookIds: ["tb-1"],
    knowledgePointIds: ["kp-7", "kp-8"],
    chapterMounts: [{ textbookId: "tb-1", chapterId: "ch-3-1" }],
    status: "draft",
    updatedAt: "2026-06-02",
  },
  {
    id: "as-3",
    title: "整式的加减 · 随堂练习",
    subject: "数学",
    level: "school",
    ownerScope: "上海市实验中学",
    questionIds: ["q-5", "q-8"],
    textbookIds: ["tb-1"],
    knowledgePointIds: ["kp-5", "kp-6"],
    chapterMounts: [],
    status: "draft",
    updatedAt: "2026-06-10",
  },
]

// 微课
export const microlessons: Microlesson[] = [
  {
    id: "ml-1",
    title: "认识负数与数轴",
    subject: "数学",
    duration: "06:42",
    level: "city",
    ownerScope: "上海市",
    viewCount: 2310,
    knowledgePointIds: ["kp-1", "kp-2"],
    chapterMounts: [{ textbookId: "tb-1", chapterId: "ch-1-1" }],
    updatedAt: "2026-05-18",
  },
  {
    id: "ml-2",
    title: "有理数的乘除法则精讲",
    subject: "数学",
    duration: "09:15",
    level: "city",
    ownerScope: "上海市",
    knowledgePointIds: ["kp-4"],
    chapterMounts: [{ textbookId: "tb-1", chapterId: "ch-1-4" }],
    updatedAt: "2026-05-25",
  },
  {
    id: "ml-3",
    title: "合并同类项技巧",
    subject: "数学",
    duration: "07:08",
    level: "school",
    ownerScope: "徐汇区第一中心小学",
    knowledgePointIds: ["kp-6"],
    chapterMounts: [],
    updatedAt: "2026-06-05",
  },
]

// 空中课堂
export const airClasses: AirClass[] = [
  {
    id: "ac-1",
    title: "有理数运算综合复习课",
    subject: "数学",
    teacher: "王明老师",
    level: "city",
    ownerScope: "上海市",
    scheduledAt: "2026-06-25 19:00",
    knowledgePointIds: ["kp-3", "kp-4"],
    chapterMounts: [{ textbookId: "tb-1", chapterId: "ch-1-3" }],
    updatedAt: "2026-05-20",
  },
  {
    id: "ac-2",
    title: "整式概念与化简专题",
    subject: "数学",
    teacher: "李芳老师",
    level: "city",
    ownerScope: "上海市",
    scheduledAt: "2026-06-28 19:00",
    knowledgePointIds: ["kp-5", "kp-6"],
    chapterMounts: [],
    updatedAt: "2026-06-07",
  },
]

// 精品资源（独立类型）：平台/区域精选优质资源包
export const premiums: Premium[] = [
  {
    id: "pm-1",
    title: "七年级（上）有理数单元精品卷",
    subject: "数学",
    category: "paper",
    description: "覆盖有理数全部核心考点的精选试卷，含分层难度与详解。",
    questionIds: ["q-1", "q-2", "q-3"],
    knowledgePointIds: ["kp-1", "kp-2", "kp-3"],
    level: "city",
    ownerScope: "上海市",
    chapterMounts: [{ textbookId: "tb-1", chapterId: "ch-1-1" }],
    usedCount: 218,
    updatedAt: "2026-05-28",
  },
  {
    id: "pm-2",
    title: "专题十 · 比和比例应用",
    subject: "数学",
    category: "special",
    description: "围绕正反比例的实际应用，按补充知识、自学例题、自我检测、巩固练习、阶段练习分板块编排，配套 10 段讲解视频。",
    questionIds: [],
    knowledgePointIds: ["kp-7"],
    level: "district",
    ownerScope: "徐汇区",
    chapterMounts: [],
    usedCount: 96,
    updatedAt: "2026-06-05",
    lockVideoUntilAnswered: true,
    sections: [
      {
        id: "sec-1",
        title: "补充知识",
        items: [
          {
            id: "it-1",
            type: "text",
            content:
              "比例问题的解题思路与方法：第一步，找出与问题有关的两种相关联的量，判断它们是否成比例、是正比例还是反比例；第二步，找出两种量的对应数值，并把未知量设为 x；第三步，根据正、反比例意义列出比例式；第四步，解比例求出 x 的值；第五步，检验并写出答句。",
          },
        ],
      },
      {
        id: "sec-2",
        title: "自学例题",
        items: [
          {
            id: "it-2",
            type: "question",
            qType: "subjective",
            label: "例1",
            stem: "买甲、乙两种笔共 210 支，甲种笔每支价值 3 元，乙种笔每支价值 4 元，两种笔用去的钱相同，甲种笔买了多少支？",
            answer: "120 支",
            analysis:
              "甲、乙两种笔单价之比为 3:4，用去的钱相同，故数量之比为 4:3。甲占总数的 4/7，甲种笔数为 210 × 4/7 = 120（支）。",
          },
          {
            id: "it-3",
            type: "question",
            qType: "subjective",
            label: "例2",
            stem: "水泥、石子、黄砂各有 5 吨，按 5:3:2 拌制某种混凝土。若用完石子，水泥缺多少吨，黄砂多多少吨？",
            answer: "水泥缺 3又1/3 吨，黄砂多 1又2/3 吨",
            analysis:
              "石子占总份数的 3/10，当石子用 5 吨时，混凝土共 5 ÷ 3/10 = 16又2/3（吨）。水泥占 1/2，应为 8又1/3 吨，故缺 8又1/3 − 5 = 3又1/3 吨；黄砂应为 3又1/3 吨，故多 3又1/3 − 5 = 1又2/3 吨。",
          },
          {
            id: "it-4",
            type: "question",
            qType: "subjective",
            label: "例3",
            stem: "有一块铜锌合金，铜与锌的比是 2:3。现加入锌 6 克，共得新合金 36 克，则新合金内铜与锌的比为多少？",
            answer: "1:2",
            analysis:
              "旧合金重 36 − 6 = 30（克），铜占 2/5，旧合金含铜 12 克、锌 18 克。新合金中铜仍 12 克，锌 18 + 6 = 24 克，故铜:锌 = 12:24 = 1:2。",
          },
          {
            id: "it-5",
            type: "question",
            qType: "subjective",
            label: "例4",
            stem: "某船第一次顺流航行 21 千米、逆流航行 4 千米；第二次在同一河道顺流航行 12 千米、逆流航行 7 千米，两次所用时间相等。顺水船速与逆水船速之比是多少？",
            answer: "3:1",
            analysis:
              "第一次比第二次顺流多行 21 − 12 = 9 千米，第二次比第一次逆流多行 7 − 4 = 3 千米，时间相等即顺流 9 千米的时间等于逆流 3 千米的时间。故顺流:逆流 = 9:3 = 3:1。",
          },
        ],
      },
      {
        id: "sec-3",
        title: "自我归纳",
        items: [
          {
            id: "it-6",
            type: "text",
            title: "学生自填区",
            content: "（留白，供学生归纳正反比例应用的解题要点）",
          },
        ],
      },
      {
        id: "sec-4",
        title: "自我检测",
        items: [
          {
            id: "it-7",
            type: "question",
            qType: "single",
            label: "1",
            stem: "某车库停放若干辆双轮摩托车和四轮小汽车，车的辆数与车的轮子数的比是 3:7。摩托车的辆数与小汽车的辆数的比是多少？",
            options: [
              { id: "o1", text: "5:1", correct: true },
              { id: "o2", text: "1:5", correct: false },
              { id: "o3", text: "3:7", correct: false },
              { id: "o4", text: "7:3", correct: false },
            ],
            answer: "5:1",
            analysis: "设摩托车 a 辆、小汽车 b 辆，轮子数 2a+4b。(a+b):(2a+4b)=3:7，解得 a:b=5:1。",
            video: { title: "视频1", url: "https://video.dianzhebi.com/topic10/v1.mp4", duration: "3:12" },
          },
          {
            id: "it-8",
            type: "question",
            qType: "subjective",
            label: "2",
            stem: "甲、乙两人步行速度比是 11:9。若由 A、B 两地同时出发相向而行，0.5 小时后相遇；若同向而行，甲追上乙需要多少小时？",
            answer: "5 小时",
            video: { title: "视频2", url: "https://video.dianzhebi.com/topic10/v2.mp4", duration: "4:05" },
          },
          {
            id: "it-9",
            type: "question",
            qType: "subjective",
            label: "3",
            stem: "小明和小方各走一段路，小明走的路程比小方多 1/5，小方用的时间比小明多 1/9。小明和小方的速度之比是多少？",
            answer: "4:3",
            video: { title: "视频3", url: "https://video.dianzhebi.com/topic10/v3.mp4", duration: "3:48" },
          },
          {
            id: "it-10",
            type: "question",
            qType: "subjective",
            label: "4",
            stem: "圆柱容器中放有一个长方体铁块。打开水龙头注水，4 分钟时水恰好没过长方体顶面，又过 21 分钟水灌满容器。已知容器高 50 厘米、长方体高 20 厘米，长方体底面积与容器底面积之比是多少？",
            answer: "5:7",
            video: { title: "视频4", url: "https://video.dianzhebi.com/topic10/v4.mp4", duration: "5:20" },
          },
        ],
      },
      {
        id: "sec-5",
        title: "巩固练习",
        items: [
          {
            id: "it-11",
            type: "question",
            qType: "subjective",
            label: "1",
            stem: "自然数 A、B 满足 1/A + 1/B = 1/182，且 A:B = 7:13。那么 B − A = ?",
            answer: "72",
            analysis: "设 A = 7k，B = 13k，1/A + 1/B = (1/7 + 1/13)/k = 6/(91k) = 1/182，故 k = 12，B − A = 6k = 72。",
            video: { title: "视频5", url: "https://video.dianzhebi.com/topic10/v5.mp4", duration: "4:32" },
          },
          {
            id: "it-12",
            type: "question",
            qType: "subjective",
            label: "2",
            stem: "某小学有三个年级，一年级占全校 25%，二、三年级人数比是 3:4，已知一年级比三年级少 40 人。一年级有多少人？",
            answer: "56",
            analysis: "二、三年级占 75%，三年级占 75% × 4/7 = 3/7。一年级比三年级少的 40 人占全校 3/7 − 25% = 5/28，故全校 40 ÷ 5/28 = 224 人，一年级 224 × 25% = 56 人。",
            video: { title: "视频6", url: "https://video.dianzhebi.com/topic10/v6.mp4", duration: "5:01" },
          },
          {
            id: "it-13",
            type: "question",
            qType: "subjective",
            label: "3",
            stem: "一段路分上坡、平路、下坡三段，路程之比 1:2:3，走各段所用时间之比 4:5:6。已知上坡速度为每小时 4 千米，全长 60 千米，走完全程用了多少小时？",
            answer: "75/8",
            analysis: "上坡占总路程 1/6，长 10 千米，时间 10/4 = 5/2 小时。平路时间 5/2 × 5/4 = 25/8，下坡时间 5/2 × 6/4 = 15/4。全程 5/2 + 25/8 + 15/4 = 75/8（小时）。",
            video: { title: "视频7", url: "https://video.dianzhebi.com/topic10/v7.mp4", duration: "6:15" },
          },
          {
            id: "it-14",
            type: "question",
            qType: "subjective",
            label: "4",
            stem: "甲、乙两仓库存货吨数比为 5:4，若由甲库取出 20 吨放到乙库，则两库存货吨数比为 5:11。两仓库原存货总吨数是多少？",
            answer: "198",
            analysis: "甲库原占总数 5/9，取出后占 4/9，差值 1/9 对应取出的部分占总数 1/11。结合取出量可解得总数为 198 吨。",
            video: { title: "视频8", url: "https://video.dianzhebi.com/topic10/v8.mp4", duration: "4:50" },
          },
        ],
      },
      {
        id: "sec-6",
        title: "阶段练习",
        items: [
          {
            id: "it-15",
            type: "question",
            qType: "subjective",
            label: "1",
            stem: "已知甲、乙两数的比为 5:6，且它们最大公约数与最小公倍数的和是 217，那么甲数是多少？",
            answer: "35",
            video: { title: "视频9", url: "https://video.dianzhebi.com/topic10/v9.mp4", duration: "3:40" },
          },
          {
            id: "it-16",
            type: "question",
            qType: "subjective",
            label: "2",
            stem: "一个长方体，长与宽的比是 2:1，宽与高的比是 3:2，已知全部棱长之和是 220cm，则这个长方体的体积是多少？",
            answer: "4500",
            video: { title: "视频10", url: "https://video.dianzhebi.com/topic10/v10.mp4", duration: "5:33" },
          },
        ],
      },
    ],
  },
  {
    id: "pm-3",
    title: "整式运算精品课件",
    subject: "数学",
    category: "courseware",
    description: "可直接用于课堂讲授的整式运算精品课件。",
    questionIds: [],
    knowledgePointIds: ["kp-5", "kp-6"],
    level: "school",
    ownerScope: "位育中学",
    chapterMounts: [],
    usedCount: 34,
    updatedAt: "2026-06-09",
  },
]
