import type {
  AirClass,
  Assignment,
  ChapterNode,
  ChapterSyncLink,
  KnowledgePoint,
  Microlesson,
  Premium,
  Question,
  QuestionVersion,
  TagDisable,
  TagItem,
  Textbook,
} from "./types"
import { BASE_SCOPE } from "./types"

export const SUBJECTS = ["数学", "语文", "英语", "物理", "化学", "生物"]
export const VERSIONS = ["人教版", "北师大版", "苏教版", "华师大版", "外研版"]
export const GRADES = ["一年级", "二年级", "三年级", "四年级", "五年级", "六年级", "七年级", "八年级", "九年级"]

export const textbooks: Textbook[] = [
  {
    id: "tb-1",
    name: "义务教育教科书·数学（七年级上册）",
    subject: "数学",
    stage: "junior",
    grade: "七年级",
    volume: "upper",
    version: "人教版",
    year: 2024,
    status: "published",
    cover: "/covers/math.png",
    updatedAt: "2026-05-12",
  },
  {
    id: "tb-2",
    name: "义务教育教科书·数学（七年级上册）",
    subject: "数学",
    stage: "junior",
    grade: "七年级",
    volume: "upper",
    version: "北师大版",
    year: 2024,
    status: "published",
    cover: "/covers/math.png",
    updatedAt: "2026-04-28",
  },
  {
    id: "tb-3",
    name: "义务教育教科书·数学（七年级上册）",
    subject: "数学",
    stage: "junior",
    grade: "七年级",
    volume: "upper",
    version: "人教版",
    year: 2019,
    status: "archived",
    cover: "/covers/math.png",
    updatedAt: "2025-09-01",
  },
  {
    id: "tb-4",
    name: "义务教育教科书·语文（八年级下册）",
    subject: "语文",
    stage: "junior",
    grade: "八年级",
    volume: "lower",
    version: "人教版",
    year: 2024,
    status: "published",
    cover: "/covers/chinese.png",
    updatedAt: "2026-03-15",
  },
  {
    id: "tb-5",
    name: "普通高中教科书·物理（必修第一册）",
    subject: "物理",
    stage: "senior",
    grade: "高一",
    volume: "full",
    version: "人教版",
    year: 2025,
    status: "draft",
    cover: "/covers/physics.png",
    updatedAt: "2026-06-10",
  },
]

// 知识点：数学七上的稳定考点，跨版本通用
export const knowledgePoints: KnowledgePoint[] = [
  { id: "kp-1", subject: "数学", group: "有理数", name: "正数与负数的概念" },
  { id: "kp-2", subject: "数学", group: "有理数", name: "数轴与相反数" },
  { id: "kp-3", subject: "数学", group: "有理数", name: "有理数的加减运算" },
  { id: "kp-4", subject: "数学", group: "有理数", name: "有理数的乘除运算" },
  { id: "kp-5", subject: "数学", group: "整式", name: "单项式与多项式" },
  { id: "kp-6", subject: "数学", group: "整式", name: "整式的加减" },
  { id: "kp-7", subject: "数学", group: "一元一次方程", name: "方程的概念" },
  { id: "kp-8", subject: "数学", group: "一元一次方程", name: "解一元一次方程" },
]

// ===================== 标签字典种子 =====================
// 平台基准（BASE_SCOPE）：所有区域共享；区域可新增专属或停用基准项。
let _tagSeq = 0
const _t = (
  dimensionKey: TagItem["dimensionKey"],
  subject: string,
  name: string,
  order: number,
  scope: string,
  tier?: number,
): TagItem => ({ id: `tag-${++_tagSeq}`, dimensionKey, subject, name, order, scope, tier })

export const tagItems: TagItem[] = [
  // 难度（通用标准，可自定义档位）
  _t("difficulty", "通用", "1星·入门", 1, BASE_SCOPE, 1),
  _t("difficulty", "通用", "2星·基础", 2, BASE_SCOPE, 2),
  _t("difficulty", "通用", "3星·中等", 3, BASE_SCOPE, 3),
  _t("difficulty", "通用", "4星·较难", 4, BASE_SCOPE, 4),
  _t("difficulty", "通用", "5星·挑战", 5, BASE_SCOPE, 5),
  // 学习水平（通用标准，单选）
  _t("learningLevel", "通用", "记忆", 1, BASE_SCOPE),
  _t("learningLevel", "通用", "理解", 2, BASE_SCOPE),
  _t("learningLevel", "通用", "应用", 3, BASE_SCOPE),
  _t("learningLevel", "通用", "分析综合", 4, BASE_SCOPE),
  // 内容领域（数学，多选）
  _t("contentDomain", "数学", "数与代数", 1, BASE_SCOPE),
  _t("contentDomain", "数学", "图形与几何", 2, BASE_SCOPE),
  _t("contentDomain", "数学", "统计与概率", 3, BASE_SCOPE),
  _t("contentDomain", "数学", "综合与实践", 4, BASE_SCOPE),
  // 核心素养（数学，多选）
  _t("literacy", "数学", "数学运算", 1, BASE_SCOPE),
  _t("literacy", "数学", "逻辑推理", 2, BASE_SCOPE),
  _t("literacy", "数学", "数学建模", 3, BASE_SCOPE),
  _t("literacy", "数学", "直观想象", 4, BASE_SCOPE),
  _t("literacy", "数学", "数据分析", 5, BASE_SCOPE),
  // 情境属性（数学，单选）
  _t("scene", "数学", "纯数学情境", 1, BASE_SCOPE),
  _t("scene", "数学", "生活情境", 2, BASE_SCOPE),
  _t("scene", "数学", "跨学科情境", 3, BASE_SCOPE),
  // 教学用途（数学，多选）
  _t("usage", "数学", "基础巩固", 1, BASE_SCOPE),
  _t("usage", "数学", "易错训练", 2, BASE_SCOPE),
  _t("usage", "数学", "课堂讲解", 3, BASE_SCOPE),
  _t("usage", "数学", "单元复习", 4, BASE_SCOPE),
  _t("usage", "数学", "拓展提升", 5, BASE_SCOPE),
  // —— 区域专属示例：徐汇区为数学“核心素养”新增本区标签 ——
  _t("literacy", "数学", "区域特色·实验探究", 6, "徐汇区"),
  // —— 区域专属示例：上海市为数学“情境属性”新增 ——
  _t("scene", "数学", "海派文化情境", 4, "上海市"),
]

// 区域停用覆盖示例：徐汇区停用基准“跨学科情境”
export const tagDisables: TagDisable[] = [
  { tagId: tagItems.find((t) => t.scope === BASE_SCOPE && t.name === "跨学科情境")!.id, scope: "徐汇区" },
]

// 章节目录：每个节点声明它覆盖的知识点
export const chapters: ChapterNode[] = [
  // 人教版数学七上（tb-1）
  { id: "ch-1", textbookId: "tb-1", parentId: null, title: "第一章 有理数", order: 1, knowledgePointIds: [] },
  { id: "ch-1-1", textbookId: "tb-1", parentId: "ch-1", title: "1.1 正数和负数", order: 1, knowledgePointIds: ["kp-1"] },
  { id: "ch-1-2", textbookId: "tb-1", parentId: "ch-1", title: "1.2 有理数", order: 2, knowledgePointIds: ["kp-2"] },
  { id: "ch-1-3", textbookId: "tb-1", parentId: "ch-1", title: "1.3 有理数的加减法", order: 3, knowledgePointIds: ["kp-3"] },
  { id: "ch-1-4", textbookId: "tb-1", parentId: "ch-1", title: "1.4 有理数的乘除法", order: 4, knowledgePointIds: ["kp-4"] },
  { id: "ch-2", textbookId: "tb-1", parentId: null, title: "第二章 整式的加减", order: 2, knowledgePointIds: [] },
  { id: "ch-2-1", textbookId: "tb-1", parentId: "ch-2", title: "2.1 整式", order: 1, knowledgePointIds: ["kp-5"] },
  { id: "ch-2-2", textbookId: "tb-1", parentId: "ch-2", title: "2.2 整式的加减", order: 2, knowledgePointIds: ["kp-6"] },
  { id: "ch-3", textbookId: "tb-1", parentId: null, title: "第三章 一元一次方程", order: 3, knowledgePointIds: [] },
  { id: "ch-3-1", textbookId: "tb-1", parentId: "ch-3", title: "3.1 从算式到方程", order: 1, knowledgePointIds: ["kp-7"] },
  { id: "ch-3-2", textbookId: "tb-1", parentId: "ch-3", title: "3.2 解一元一次方程", order: 2, knowledgePointIds: ["kp-8"] },
  // 北师大版数学七上（tb-2，结构不同，知识点对应一致）
  { id: "bs-1", textbookId: "tb-2", parentId: null, title: "第一章 丰富的图形世界", order: 1, knowledgePointIds: [] },
  { id: "bs-2", textbookId: "tb-2", parentId: null, title: "第二章 有理数及其运算", order: 2, knowledgePointIds: [] },
  { id: "bs-2-1", textbookId: "tb-2", parentId: "bs-2", title: "2.1 有理数", order: 1, knowledgePointIds: ["kp-1"] },
  { id: "bs-2-2", textbookId: "tb-2", parentId: "bs-2", title: "2.2 数轴", order: 2, knowledgePointIds: ["kp-2"] },
  { id: "bs-2-3", textbookId: "tb-2", parentId: "bs-2", title: "2.3 有理数的加减法", order: 3, knowledgePointIds: ["kp-3"] },
  { id: "bs-2-4", textbookId: "tb-2", parentId: "bs-2", title: "2.4 有理数的乘除法", order: 4, knowledgePointIds: ["kp-4"] },
  { id: "bs-3", textbookId: "tb-2", parentId: null, title: "第三章 整式及其加减", order: 3, knowledgePointIds: ["kp-5", "kp-6"] },
  // 2019 旧人教版数学七上（tb-3）
  { id: "old-1", textbookId: "tb-3", parentId: null, title: "第一章 有理数", order: 1, knowledgePointIds: [] },
  { id: "old-1-1", textbookId: "tb-3", parentId: "old-1", title: "1.1 正数和负数", order: 1, knowledgePointIds: ["kp-1"] },
  { id: "old-1-2", textbookId: "tb-3", parentId: "old-1", title: "1.2 有理数", order: 2, knowledgePointIds: ["kp-2"] },
  { id: "old-2", textbookId: "tb-3", parentId: null, title: "第二章 整式的加减", order: 2, knowledgePointIds: [] },
  { id: "old-2-1", textbookId: "tb-3", parentId: "old-2", title: "2.1 整式", order: 1, knowledgePointIds: ["kp-5"] },
]

// 题目：打知识点标签，章节锚点可由知识点自动归集；带级别/归属
// rawQuestions 不含版本结构，下方 normalizeQuestion 会自动补 v1（含历史演示版本）
const rawQuestions: Omit<Question, "version" | "versions">[] = [
  {
    id: "q-1",
    stem: "下列各数中，是负数的是（　）。",
    type: "single",
    subject: "数学",
    difficulty: 1,
    level: "city",
    ownerScope: "上海市",
    options: [
      { key: "A", content: "$-3$" },
      { key: "B", content: "$0$" },
      { key: "C", content: "$2.5$" },
      { key: "D", content: "$|-1|$" },
    ],
    answer: "A",
    analysis: "负数是小于 0 的数，$-3 < 0$，故选 A。",
    knowledgePointIds: ["kp-1"],
    literacy: ["数学运算"],
    cognitive: "理解",
    usage: ["基础巩固", "课堂讲解"],
    scene: "纯数学情景",
    videoTitle: "认识负数与相反数",
    videoDuration: "06:12",
    usedCount: 326,
    studentCount: 1280,
    chapterMounts: [
      { textbookId: "tb-1", chapterId: "ch-1-1" },
      { textbookId: "tb-2", chapterId: "bs-2-1" },
    ],
    updatedAt: "2026-05-20",
  },
  {
    id: "q-2",
    stem: "计算：$(-7) + (+3) - (-5) = $ ______。",
    type: "fill",
    subject: "数学",
    difficulty: 2,
    level: "city",
    ownerScope: "上海市",
    answer: "$1$",
    analysis: "原式 $= -7 + 3 + 5 = 1$。",
    knowledgePointIds: ["kp-3"],
    literacy: ["数学运算"],
    cognitive: "应用",
    usage: ["课后练习"],
    videoTitle: "有理数加减混合运算",
    videoDuration: "08:30",
    usedCount: 91,
    studentCount: 540,
    chapterMounts: [
      { textbookId: "tb-1", chapterId: "ch-1-3" },
      { textbookId: "tb-2", chapterId: "bs-2-3" },
    ],
    updatedAt: "2026-05-18",
  },
  {
    id: "q-3",
    stem: "判断：两个负数相乘，积一定为正数。（　）",
    type: "judge",
    subject: "数学",
    difficulty: 2,
    level: "city",
    ownerScope: "上海市",
    answer: "正确",
    knowledgePointIds: ["kp-4"],
    chapterMounts: [
      { textbookId: "tb-1", chapterId: "ch-1-4" },
      { textbookId: "tb-2", chapterId: "bs-2-4" },
    ],
    updatedAt: "2026-05-15",
  },
  {
    id: "q-4",
    stem: "解方程：3x − 5 = 2x + 7，并写出完整求解过程。",
    type: "subjective",
    subject: "数学",
    difficulty: 3,
    level: "district",
    ownerScope: "徐汇区",
    answer: "x = 12",
    knowledgePointIds: ["kp-8"],
    chapterMounts: [{ textbookId: "tb-1", chapterId: "ch-3-2" }],
    updatedAt: "2026-06-01",
  },
  {
    id: "q-5",
    stem: "下列式子中，属于单项式的有（　）。",
    type: "multiple",
    subject: "数学",
    difficulty: 3,
    level: "city",
    ownerScope: "上海市",
    knowledgePointIds: ["kp-5"],
    chapterMounts: [
      { textbookId: "tb-1", chapterId: "ch-2-1" },
      { textbookId: "tb-2", chapterId: "bs-3" },
    ],
    updatedAt: "2026-06-08",
  },
  {
    id: "q-6",
    stem: "在数轴上，表示 −2 的点到原点的距离是 ______。",
    type: "fill",
    subject: "数学",
    difficulty: 1,
    level: "school",
    ownerScope: "上海市实验中学",
    answer: "2",
    knowledgePointIds: ["kp-2"],
    chapterMounts: [
      { textbookId: "tb-1", chapterId: "ch-1-2" },
      { textbookId: "tb-2", chapterId: "bs-2-2" },
    ],
    updatedAt: "2026-06-09",
  },
  {
    id: "q-7",
    stem: "计算：(−12) ÷ (−4) × 3 = ______。",
    type: "fill",
    subject: "数学",
    difficulty: 2,
    level: "district",
    ownerScope: "浦东新区",
    answer: "9",
    knowledgePointIds: ["kp-4"],
    chapterMounts: [{ textbookId: "tb-1", chapterId: "ch-1-4" }],
    updatedAt: "2026-06-09",
  },
  {
    id: "q-8",
    stem: "合并同类项：3a + 5a − 2a = ______。",
    type: "fill",
    subject: "数学",
    difficulty: 2,
    level: "school",
    ownerScope: "上海市实验中学",
    answer: "6a",
    knowledgePointIds: ["kp-6"],
    chapterMounts: [],
    updatedAt: "2026-06-11",
  },
  {
    id: "q-9",
    stem: "下列各式是方程的是（　）。A. 3+2  B. x−1=0  C. a>b  D. 2x",
    type: "single",
    subject: "数学",
    difficulty: 1,
    level: "city",
    ownerScope: "上海市",
    answer: "B",
    knowledgePointIds: ["kp-7"],
    chapterMounts: [],
    updatedAt: "2026-06-11",
  },
  {
    id: "q-10",
    stem: "若 |x| = 5，则 x = ______。",
    type: "fill",
    subject: "数学",
    difficulty: 2,
    level: "city",
    ownerScope: "上海市",
    answer: "±5",
    knowledgePointIds: ["kp-1", "kp-2"],
    chapterMounts: [],
    updatedAt: "2026-06-12",
  },
]

// 为每道原始题目补一个 v1（镜像顶层内容与统计），使旧数据自然拥有版本结构
function normalizeQuestion(raw: Omit<Question, "version" | "versions">): Question {
  const v1: QuestionVersion = {
    version: 1,
    status: "published",
    stem: raw.stem,
    type: raw.type,
    options: raw.options,
    answer: raw.answer,
    analysis: raw.analysis,
    usedCount: raw.usedCount,
    studentCount: raw.studentCount,
    correctRate: undefined,
    changeNote: "初始版本",
    createdAt: raw.updatedAt,
  }
  return { ...raw, version: 1, versions: [v1] }
}

// 多版本演示：q-1 经历过一次修订（v1 表述不清 → v2 改好，正确率提升）
const MULTI_VERSION: Record<string, QuestionVersion[]> = {
  "q-1": [
    {
      version: 1,
      status: "archived",
      stem: "下列各数中，哪个是负数？",
      type: "single",
      options: [
        { key: "A", content: "$-3$" },
        { key: "B", content: "$0$" },
        { key: "C", content: "$2.5$" },
        { key: "D", content: "$|-1|$" },
      ],
      answer: "A",
      analysis: "负数是小于 0 的数。",
      usedCount: 120,
      studentCount: 460,
      correctRate: 63,
      changeNote: "初始版本",
      createdAt: "2026-03-10",
    },
    {
      version: 2,
      status: "published",
      stem: "下列各数中，是负数的是（　）。",
      type: "single",
      options: [
        { key: "A", content: "$-3$" },
        { key: "B", content: "$0$" },
        { key: "C", content: "$2.5$" },
        { key: "D", content: "$|-1|$" },
      ],
      answer: "A",
      analysis: "负数是小于 0 的数，$-3 < 0$，故选 A。",
      usedCount: 206,
      studentCount: 820,
      correctRate: 81,
      changeNote: "优化题干表述，明确选项作答方式，正确率由 63% 提升至 81%",
      createdAt: "2026-05-20",
    },
  ],
}

export const questions: Question[] = rawQuestions.map((raw) => {
  const multi = MULTI_VERSION[raw.id]
  if (!multi) return normalizeQuestion(raw)
  const current = multi[multi.length - 1]
  return {
    ...raw,
    // 顶层内容/统计镜像当前版本
    stem: current.stem,
    type: current.type,
    options: current.options,
    answer: current.answer,
    analysis: current.analysis,
    usedCount: current.usedCount,
    studentCount: current.studentCount,
    version: current.version,
    versions: multi,
  }
})

// 教材同步关系：人教版（tb-1） ⇄ 北师大版（tb-2），逐目录手工对应
export const syncLinks: ChapterSyncLink[] = [
  {
    id: "sl-1",
    fromTextbookId: "tb-1",
    fromChapterId: "ch-1-1",
    toTextbookId: "tb-2",
    toChapterId: "bs-2-1",
    syncTypes: ["question", "assignment"],
  },
  {
    id: "sl-2",
    fromTextbookId: "tb-1",
    fromChapterId: "ch-1-3",
    toTextbookId: "tb-2",
    toChapterId: "bs-2-3",
    syncTypes: ["question", "assignment", "microlesson"],
  },
  {
  id: "sl-3",
  fromTextbookId: "tb-1",
  fromChapterId: "ch-2-1",
  toTextbookId: "tb-2",
  toChapterId: "bs-3",
  syncTypes: ["question", "microlesson", "airclass"],
  },
  // tb-1 同时同步到 tb-3（一对多：同一主教材 → 多套目标教材）
  {
  id: "sl-4",
  fromTextbookId: "tb-1",
  fromChapterId: "ch-1-1",
  toTextbookId: "tb-3",
  toChapterId: "old-1-1",
  syncTypes: ["question", "assignment"],
  },
  {
  id: "sl-5",
  fromTextbookId: "tb-1",
  fromChapterId: "ch-2-1",
  toTextbookId: "tb-3",
  toChapterId: "old-2-1",
  syncTypes: ["question"],
  },
  ]

export const assignments: Assignment[] = [
  {
    id: "as-1",
    title: "第一章 有理数 · 课后基础练",
    subject: "数学",
    level: "city",
    ownerScope: "上海市",
    questionIds: ["q-1", "q-2", "q-3"],
    textbookIds: ["tb-1", "tb-2"],
    knowledgePointIds: ["kp-1", "kp-2"],
    chapterMounts: [{ textbookId: "tb-1", chapterId: "ch-1-1" }],
    status: "published",
    assignedClasses: 6,
    usedCount: 142,
    updatedAt: "2026-05-22",
  },
  {
    id: "as-2",
    title: "一元一次方程 · 专项提升",
    subject: "数学",
    level: "district",
    ownerScope: "徐汇区",
    questionIds: ["q-4"],
    textbookIds: ["tb-1"],
    knowledgePointIds: ["kp-7", "kp-8"],
    chapterMounts: [{ textbookId: "tb-1", chapterId: "ch-3-1" }],
    status: "draft",
    updatedAt: "2026-06-02",
  },
  {
    id: "as-3",
    title: "整式的加减 · 随堂练习",
    subject: "数学",
    level: "school",
    ownerScope: "上海市实验中学",
    questionIds: ["q-5", "q-8"],
    textbookIds: ["tb-1"],
    knowledgePointIds: ["kp-5", "kp-6"],
    chapterMounts: [],
    status: "draft",
    updatedAt: "2026-06-10",
  },
]

// 微课
export const microlessons: Microlesson[] = [
  {
    id: "ml-1",
    title: "认识负数与数轴",
    subject: "数学",
    grade: "七年级",
    duration: "06:42",
    level: "city",
    ownerScope: "上海市",
    videoUrl: "https://video.dianzhebi.com/ml/ml1.mp4",
    creatorName: "王明",
    creatorOrg: "上海市徐汇区第一中心小学",
    intro: "结合生活实例引入负数概念，并借助数轴理解正负数的相对位置与大小比较。",
    category: "sync",
    status: "published",
    viewCount: 2310,
    knowledgePointIds: ["kp-1", "kp-2"],
    chapterMounts: [{ textbookId: "tb-1", chapterId: "ch-1-1" }],
    attachments: [{ id: "att-1", name: "认识负数-配套练习.pdf", size: "1.2 MB" }],
    updatedAt: "2026-05-18",
  },
  {
    id: "ml-2",
    title: "有理数的乘除法则精讲",
    subject: "数学",
    grade: "七年级",
    duration: "09:15",
    level: "city",
    ownerScope: "上海市",
    videoUrl: "https://video.dianzhebi.com/ml/ml2.mp4",
    creatorName: "李华",
    creatorOrg: "上海市教育研究院",
    intro: "系统梳理有理数乘除法的符号法则与运算顺序，配套典型例题逐步讲解。",
    category: "topic",
    status: "published",
    viewCount: 1875,
    knowledgePointIds: ["kp-4"],
    chapterMounts: [{ textbookId: "tb-1", chapterId: "ch-1-4" }],
    updatedAt: "2026-05-25",
  },
  {
    id: "ml-3",
    title: "合并同类项技巧",
    subject: "数学",
    grade: "七年级",
    duration: "07:08",
    level: "school",
    ownerScope: "徐汇区第一中心小学",
    creatorName: "张伟",
    creatorOrg: "徐汇区第一中心小学",
    intro: "通过分类与对比，掌握快速识别同类项并准确合并的实用技巧。",
    category: "review",
    status: "draft",
    knowledgePointIds: ["kp-6"],
    chapterMounts: [],
    updatedAt: "2026-06-05",
  },
]

// 空中课堂
export const airClasses: AirClass[] = [
  {
    id: "ac-1",
    title: "有理数运算综合复习课",
    subject: "数学",
    teacher: "王明老师",
    level: "city",
    ownerScope: "上海市",
    scheduledAt: "2026-06-25 19:00",
    knowledgePointIds: ["kp-3", "kp-4"],
    chapterMounts: [{ textbookId: "tb-1", chapterId: "ch-1-3" }],
    updatedAt: "2026-05-20",
  },
  {
    id: "ac-2",
    title: "整式概念与化简专题",
    subject: "数学",
    teacher: "李芳老师",
    level: "city",
    ownerScope: "上海市",
    scheduledAt: "2026-06-28 19:00",
    knowledgePointIds: ["kp-5", "kp-6"],
    chapterMounts: [],
    updatedAt: "2026-06-07",
  },
]

// 精品资源（独立类型）：平台/区域精选优质资源包
export const premiums: Premium[] = [
  {
    id: "pm-1",
    title: "七年级（上）有理数单元精品卷",
    subject: "数学",
    description: "覆盖有理数全部核心考点的精选试卷，每题配套讲解视频。",
    knowledgePointIds: ["kp-1", "kp-2", "kp-3"],
    level: "city",
    ownerScope: "上海市",
    chapterMounts: [{ textbookId: "tb-1", chapterId: "ch-1-1" }],
    usedCount: 218,
    updatedAt: "2026-05-28",
    items: [
      {
        id: "pm1-q1",
        qType: "single",
        label: "1",
        stem: "下列各数中，是负数的是（　）",
        options: [
          { id: "o1", text: "−3", correct: true },
          { id: "o2", text: "0", correct: false },
          { id: "o3", text: "2.5", correct: false },
          { id: "o4", text: "+7", correct: false },
        ],
        answer: "−3",
        analysis: "负数是小于 0 的数，只有 −3 小于 0。",
        video: { title: "讲解视频", url: "https://video.dianzhebi.com/pm1/v1.mp4", duration: "2:35" },
      },
      {
        id: "pm1-q2",
        qType: "fill",
        label: "2",
        stem: "−5 的相反数是＿＿，绝对值是＿＿。",
        answer: "5；5",
        analysis: "相反数只改变符号，|−5| = 5。",
        video: { title: "讲解视频", url: "https://video.dianzhebi.com/pm1/v2.mp4", duration: "1:58" },
      },
      {
        id: "pm1-q3",
        qType: "subjective",
        label: "3",
        stem: "计算：(−12) + 8 − (−5) × 2。",
        answer: "6",
        analysis: "先算乘法：(−5) × 2 = −10，原式 = −12 + 8 − (−10) = −12 + 8 + 10 = 6。",
        video: { title: "讲解视频", url: "https://video.dianzhebi.com/pm1/v3.mp4", duration: "3:20" },
      },
    ],
  },
  {
    id: "pm-2",
    title: "比和比例应用精选题包",
    subject: "数学",
    description: "围绕正反比例的实际应用精选题目，每题配套讲解视频。",
    knowledgePointIds: ["kp-7"],
    level: "district",
    ownerScope: "徐汇区",
    chapterMounts: [{ textbookId: "tb-1", chapterId: "ch-1-4" }],
    usedCount: 96,
    updatedAt: "2026-06-05",
    items: [
      {
        id: "pm2-q1",
        qType: "single",
        label: "1",
        stem: "某车库停放若干辆双轮摩托车和四轮小汽车，车的辆数与车的轮子数的比是 3:7。摩托车的辆数与小汽车的辆数的比是多少？",
        options: [
          { id: "o1", text: "5:1", correct: true },
          { id: "o2", text: "1:5", correct: false },
          { id: "o3", text: "3:7", correct: false },
          { id: "o4", text: "7:3", correct: false },
        ],
        answer: "5:1",
        analysis: "设摩托车 a 辆、小汽车 b 辆，轮子数 2a+4b。(a+b):(2a+4b)=3:7，解得 a:b=5:1。",
        video: { title: "讲解视频", url: "https://video.dianzhebi.com/topic10/v1.mp4", duration: "3:12" },
      },
      {
        id: "pm2-q2",
        qType: "subjective",
        label: "2",
        stem: "买甲、乙两种笔共 210 支，甲种笔每支价值 3 元，乙种笔每支价值 4 元，两种笔用去的钱相同，甲种笔买了多少支？",
        answer: "120 支",
        analysis:
          "甲、乙两种笔单价之比为 3:4，用去的钱相同，故数量之比为 4:3。甲占总数的 4/7，甲种笔数为 210 × 4/7 = 120（支）。",
        video: { title: "讲解视频", url: "https://video.dianzhebi.com/topic10/v2.mp4", duration: "4:05" },
      },
      {
        id: "pm2-q3",
        qType: "subjective",
        label: "3",
        stem: "有一块铜锌合金，铜与锌的比是 2:3。现加入锌 6 克，共得新合金 36 克，则新合金内铜与锌的比为多少？",
        answer: "1:2",
        analysis:
          "旧合金重 36 − 6 = 30（克），铜占 2/5，旧合金含铜 12 克、锌 18 克。新合金中铜仍 12 克，锌 18 + 6 = 24 克，故铜:锌 = 12:24 = 1:2。",
        video: { title: "讲解视频", url: "https://video.dianzhebi.com/topic10/v3.mp4", duration: "3:48" },
      },
      {
        id: "pm2-q4",
        qType: "subjective",
        label: "4",
        stem: "甲、乙两人步行速度比是 11:9。若由 A、B 两地同时出发相向而行，0.5 小时后相遇；若同向而行，甲追上乙需要多少小时？",
        answer: "5 小时",
        analysis: "相向 0.5 小时的路程差，用速度差追及即可求得同向追及时间为 5 小时。",
        video: { title: "讲解视频", url: "https://video.dianzhebi.com/topic10/v4.mp4", duration: "5:20" },
      },
      {
        id: "pm2-q5",
        qType: "subjective",
        label: "5",
        stem: "自然数 A、B 满足 1/A + 1/B = 1/182，且 A:B = 7:13。那么 B − A = ?",
        answer: "72",
        analysis: "设 A = 7k，B = 13k，1/A + 1/B = (1/7 + 1/13)/k = 6/(91k) = 1/182，故 k = 12，B − A = 6k = 72。",
        video: { title: "讲解视频", url: "https://video.dianzhebi.com/topic10/v5.mp4", duration: "4:32" },
      },
      {
        id: "pm2-q6",
        qType: "subjective",
        label: "6",
        stem: "一个长方体，长与宽的比是 2:1，宽与高的比是 3:2，已知全部棱长之和是 220cm，则这个长方体的体积是多少？",
        answer: "4500",
        analysis: "长:宽:高 = 6:3:2，一组长宽高之和为 (6+3+2)k = 11k，4 组棱长之和 44k = 220，k = 5，体积 30×15×10 = 4500。",
        video: { title: "讲解视频", url: "https://video.dianzhebi.com/topic10/v6.mp4", duration: "5:33" },
      },
    ],
  },
  {
    id: "pm-3",
    title: "整式运算精选题包",
    subject: "数学",
    description: "整式加减与乘法的典型题目，每题配套讲解视频。",
    knowledgePointIds: ["kp-5", "kp-6"],
    level: "school",
    ownerScope: "位育中学",
    chapterMounts: [],
    usedCount: 34,
    updatedAt: "2026-06-09",
    items: [
      {
        id: "pm3-q1",
        qType: "subjective",
        label: "1",
        stem: "化简：3(2a − b) − 2(a − 3b)。",
        answer: "4a + 3b",
        analysis: "去括号：6a − 3b − 2a + 6b = 4a + 3b。",
        video: { title: "讲解视频", url: "https://video.dianzhebi.com/pm3/v1.mp4", duration: "2:48" },
      },
      {
        id: "pm3-q2",
        qType: "judge",
        label: "2",
        stem: "判断：单项式 −3x²y 的次数是 2。",
        answer: "错",
        analysis: "次数为所有字母指数之和 2 + 1 = 3，故命题错误。",
        video: { title: "讲解视频", url: "https://video.dianzhebi.com/pm3/v2.mp4", duration: "1:40" },
      },
    ],
  },
]
